# cloudbuild.yaml

# Replace fleet-cyclist-299216 with your GCP project ID
# Replace plumber_test with the desired Cloud Run service name (e.g. hello-world)
# Replace us-central1 with the GCP region you are deploying to (e.g. asia-northeast1)

steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/[PROJECT-NAME]/gsheets_plumber', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/[PROJECT-NAME]/gsheets_plumber']
